version: '3'
services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=christ
      - MONGO_PASSWORD=passchrist
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=christ
      - MONGO_INITDB_ROOT_PASSWORD=passchrist
