version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=christ
      - MONGO_INITDB_ROOT_PASSWORD=passchrist
    volumes:
      - mongodb:/data/db

  redis:
    image: redis

volumes:
  mongodb: